spring:
  zipkin:
    base-url: http://123.56.152.42:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://123.56.152.42:3308/gulimall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.152.42:8848
    sentinel:
      transport:
        dashboard: localhost:8100
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 123.56.152.42
    port: 6379
  application:
    name: gulimall-product
  thymeleaf:
    cache: false
    #引入本项目的静态资源
#  mvc:
#    static-path-pattern: /static/**
#    resources:
#      static-locations: classpath:/static/

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 #逻辑已删除值（默认为1）
      logic-not-delete-value: 0 #逻辑未删除值（默认为0）
server:
  port: 9100
logging:
  level:
    com.atguigu.gulimall: debug
# 自定义线程池参数
gulimall:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300
management:
  endpoints:
    web:
      exposure:
        include: '*'

