server:
  port: 20000
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: gulimall-auth-server
  thymeleaf:
    cache: false
#  #引入本项目的静态资源,若不适用nginx则使用下面配置
#  mvc:
#    static-path-pattern: /static/**
#    resources:
#      static-locations: classpath:/static/
