server:
  port: 20000
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.152.42:8848

  thymeleaf:
    cache: false
  #引入本项目的静态资源
  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/
