spring:
  redis:
    host: 123.56.152.42
    port: 6379
  application:
    name: gulimall-seckill
  session:
    store-type: redis
  rabbitmq:
    host: #
    username: niceseason
    password: mo19960729
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.152.42:8848
    sentinel:
      transport:
        dashboard: localhost:8100
  zipkin:
    base-url: http://123.56.152.42:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 15000
#        默认情况下，sentinel是不会对feign进行监控的，需要开启配置
feign:
  sentinel:
    enabled: true

