server:
  port: 9000

spring:
  zipkin:
    base-url: http://123.56.152.42:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
  sentinel:
    transport:
      dashboard: localhost:8100
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://123.56.152.42:3308/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 123.56.152.42
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
# 自定义线程池参数
gulimall:
  thread:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveTime: 300


management:
  endpoints:
    web:
      exposure:
        include: '*'
