spring:
  application:
    name: gulimall-search
  zipkin:
    base-url: http://123.56.152.42:9411
    sender:
      type: web
    discovery-client-enabled: false
    #采样取值介于 0到1之间，1则表示全部收集
    sleuth:
      sampler:
        probability: 1
  redis:
    host: 123.56.152.42
    session:
      store-type: redis
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.152.42:8848
      sentinel:
        transport:
          dashboard: localhost:8100
#  elasticsearch:
#    rest:
#      uris: http://192.168.1.179:9200
server:
  port: 12000
logging:
  level:
    io.niceseason.gulimall.search.service: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
