server:
  port: 3300
spring:
  zipkin:
    base-url: http://123.56.152.42:9411
    sender:
      type: web
    discovery-client-enabled: false
    #采样取值介于 0到1之间，1则表示全部收集
    sleuth:
      sampler:
        probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.152.42:8848
    sentinel:
      transport:
        dashboard: localhost:8100
    alicloud:
      access-key: LTAI4FwvfjSycd1APnuG9bjj
      secret-key: O6xaxyiWfSIitcOkSuK27ju4hXT5Hl
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-hello

  application:
    name: gulimall-third-party
  redis:
    host: 123.56.152.42
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: '*'
#        默认情况下，sentinel是不会对feign进行监控的，需要开启配置
feign:
  sentinel:
    enabled: true
