server:
  port: 11000

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://123.56.152.42:3308/gulimall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://123.56.152.42:9411
    sender:
      type: web
    discovery-client-enabled: false
    #采样取值介于 0到1之间，1则表示全部收集
    sleuth:
      sampler:
        probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 123.56.152.42:8848
    sentinel:
      transport:
        dashboard: localhost:8100
  application:
    name: gulimall-ware

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    host: 123.56.152.42
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual
    port: 5672
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.atguigu: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
